import {LOGIN, LOGOUT, USER_INFO, ROUTES, RESET_PASSWORD, SET_PASSWORD, VALIDATE_TOKEN} from '@/services/api'
import {request, METHOD, removeAuthorization} from '@/utils/request'


/**
 * Sign in to the service
 * @param username The account name
 * @param password Account password
 * @returns {Promise<AxiosResponse<T>>}
 */
export async function login(username, password) {
  return request(LOGIN, METHOD.POST, {
    username: username,
    password: password
  })
}

/**
 * Ask for new password or recovery
 * @param email The email address
 * @returns {Promise<AxiosResponse<T>>}
 */
 export async function reset_password(email) {
  return request(RESET_PASSWORD, METHOD.POST, {
    email: email
  })
}

/**
 * Set the new password
 * @param token The token generated by the server
 * @param password The new password
 * @returns {Promise<AxiosResponse<T>>}
 */
 export async function set_password(token, password) {
  return request(SET_PASSWORD, METHOD.POST, {
    token: token,
    password: password
  })
}

/**
 * VALIDATE TOKEN
 * @param token The token generated by the server
 * @returns {Promise<AxiosResponse<T>>}
 */
 export async function validate_token(token) {
  return request(VALIDATE_TOKEN, METHOD.POST, {
    token: token,
  })
}

export async function getRoutesConfig() {
  return request(ROUTES, METHOD.GET)
}

/**
 * GET USER INFO
 * @returns {Promise<AxiosResponse<T>>}
 */
export async function getUserInfo(id) {
  return request(USER_INFO + id, METHOD.GET)
}

export async function logoutreq() {
  return request(LOGOUT, METHOD.POST)
}

/**
 * Cerrar sesión
 */
export function logout() {
  localStorage.removeItem(process.env.VUE_APP_NEAR_KEY)
  // localStorage.removeItem(process.env.VUE_APP_PERMISSIONS_KEY)
  // localStorage.removeItem(process.env.VUE_APP_ROLES_KEY)

  removeAuthorization()
}

export const avatars = [
  "https://biterchecker.com/dv/portal/062de866-96f3-4e64-b44c-8a032b4e7e6e.jpeg",
  "https://biterchecker.com/dv/portal/24b0c649-297a-45bc-b7d9-d1efd010dd83.jpeg",
  "https://biterchecker.com/dv/portal/e9def72e-6b60-4aae-b518-4ef383d030ac.jpeg",
  "https://biterchecker.com/dv/portal/a37c8809-f7b9-46a9-9cad-cbf1825dd44b.jpeg",
  "https://biterchecker.com/dv/portal/6cc097e6-6d55-46e4-b411-723f1a0d375a.jpeg",
  "https://biterchecker.com/dv/portal/af1629d1-8b94-4619-86cf-d1a4c418a90c.jpeg",
  "https://biterchecker.com/dv/portal/23719965-6863-456f-a108-09d39b924118.jpeg",
  "https://biterchecker.com/dv/portal/53b51188-4ea2-4897-87b1-3b3c86cca0f3.jpeg",
  "https://biterchecker.com/dv/portal/2d7bcef2-314a-4a1c-b324-a9d6861f109c.jpeg",
  "https://biterchecker.com/dv/portal/512b8dca-654e-4737-8315-6940956cef9a.jpeg",
]

export default {
  login,
  logout,
  getRoutesConfig,
  avatars,
}
